/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
 * Generated on: 15-Feb-2023 10:16:48
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II
 * Numerator Length    : 5
 * Denominator Length  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2022a.app/extern/include/tmwtypes.h 
 */
const int NL = 5;
const real64_T NUM[5] = {
    0.01488697472657, -0.02695899404537,  0.03705935223574, -0.02695899404537,
    0.01488697472657
};
const int DL = 5;
const real64_T DEN[5] = {
                   1,   -3.338693232847,    4.401916486793,   -2.691625646031,
     0.6428936122854
};
