/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.12 and Signal Processing Toolbox 9.0.
 * Generated on: 15-Feb-2023 10:10:48
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 29
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2022a.app/extern/include/tmwtypes.h 
 */
const int BL = 29;
const real64_T B[29] = {
    0.01080096024942, 0.009150882313605, 0.007511904549456,0.0005792030769843,
   -0.01127376170725, -0.02515190942132, -0.03590095692545, -0.03739762488425,
   -0.02453046490484,  0.00471963858602,  0.04788555515624,  0.09797523269544,
     0.1449637668957,   0.1784338566514,   0.1905580972352,   0.1784338566514,
     0.1449637668957,  0.09797523269544,  0.04788555515624,  0.00471963858602,
   -0.02453046490484, -0.03739762488425, -0.03590095692545, -0.02515190942132,
   -0.01127376170725,0.0005792030769843, 0.007511904549456, 0.009150882313605,
    0.01080096024942
};
